version: "3.8"

services:
  mysql-service:
    image: mysql:8.0
    container_name: hrms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hrms_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - hrms-network

  backend:
    image: ritujadesale/hrms-backend:latest
    container_name: hrms-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/hrms_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8080"
    depends_on:
      - mysql-service
    networks:
      - hrms-network

  frontend:
    image: ritujadesale/hrms-frontend:latest
    container_name: hrms-frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - hrms-network

networks:
  hrms-network:
    driver: bridge

volumes:
  mysql-data:
